version: 2.1
orbs:
  node: circleci/node@3.0.1
jobs:
  lint:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: latest
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn lint
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          install-yarn: true
          install-npm: false
          node-version: latest
      - node/install-packages:
          pkg-manager: yarn
      - run: yarn test --runInBand
workflows:
  build-and-test:
    jobs:
      - lint
      - test
